name: GTAMCMechanics
version: '1.0'
main: org.server.gtamc.GTAMC
api-version: '1.25'
depend: [Wanted]
commands:
  start_airdrops:
    description: Starts airdrop spawning
    usage: /airdrops start
  stop_airdrops:
    description: Stop airdrop spawning
    usage: /airdrops stop
